/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ResumesIndexRouteImport } from './routes/resumes.index'
import { Route as ResumesResumeIdRouteImport } from './routes/resumes.$resumeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdRoute = ResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/resumes/': typeof ResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/jobs': typeof JobsIndexRoute
  '/resumes': typeof ResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/matches': typeof MatchesRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/resumes/': typeof ResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/matches'
    | '/resume'
    | '/settings'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/jobs/'
    | '/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/matches'
    | '/resume'
    | '/settings'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/jobs'
    | '/resumes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/matches'
    | '/resume'
    | '/settings'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/jobs/'
    | '/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MatchesRoute: typeof MatchesRoute
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ResumesResumeIdRoute: typeof ResumesResumeIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId': {
      id: '/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MatchesRoute: MatchesRoute,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ResumesResumeIdRoute: ResumesResumeIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
